"use strict";
const $=id=>document.getElementById(id);
let adminKey=sessionStorage.getItem("lf.admin")||"";
let activePairing=null;
const escapeText=value=>String(value??"");
function toast(message){const node=$("toast");node.textContent=escapeText(message);node.classList.add("show");clearTimeout(node._timer);node._timer=setTimeout(()=>node.classList.remove("show"),3200)}
async function api(path,options={}){const headers=new Headers(options.headers||{});headers.set("X-Admin-Key",adminKey);if(options.body&&!headers.has("Content-Type"))headers.set("Content-Type","application/json");const response=await fetch("/owner-api"+path,{...options,headers});let payload={};try{payload=await response.json()}catch{}if(response.status===401){lockDashboard();throw new Error("The admin key is incorrect or has changed.")}if(!response.ok)throw new Error(payload.detail||`Request failed (${response.status})`);return payload}
function setBusy(button,busy,label){if(busy){button.dataset.label=button.textContent;button.textContent=label;button.disabled=true}else{button.textContent=button.dataset.label||button.textContent;button.disabled=false}}
function unlockDashboard(){sessionStorage.setItem("lf.admin",adminKey);$("unlockView").hidden=true;$("dashboardView").hidden=false;$("backendState").classList.add("online");$("backendState").querySelector("b").textContent="Owner connected"}
function lockDashboard(){adminKey="";sessionStorage.removeItem("lf.admin");$("adminKey").value="";$("unlockView").hidden=false;$("dashboardView").hidden=true;$("backendState").classList.remove("online");$("backendState").querySelector("b").textContent="Locked"}
function formatSeen(value){if(!value)return"Never";const date=new Date(value);return Number.isNaN(date.valueOf())?"Unknown":new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(date)}
function updateSummary(summary={}){$("totalCount").textContent=summary.total??0;$("enabledCount").textContent=summary.enabled??0;$("onlineCount").textContent=summary.online??0}
function clientRow(client){const row=document.createElement("article");row.className="client";const name=document.createElement("div");name.className="client-name";const dot=document.createElement("i");if(client.online)dot.className="online";const copy=document.createElement("div");const title=document.createElement("b");title.textContent=escapeText(client.name);const platform=document.createElement("small");platform.textContent=escapeText(client.platform||"unknown");copy.append(title,platform);name.append(dot,copy);const meta=document.createElement("div");meta.className="client-meta";const seen=document.createElement("span");seen.textContent=`Last active: ${formatSeen(client.last_seen)}`;const address=document.createElement("span");address.textContent=`Last address: ${escapeText(client.last_ip||"Not recorded")}`;meta.append(seen,address);const toggle=document.createElement("button");toggle.className=`access-toggle${client.enabled?"":" paused"}`;toggle.textContent=client.enabled?"Allowed":"Paused";toggle.addEventListener("click",()=>changeAccess(client.id,!client.enabled,toggle));const revoke=document.createElement("button");revoke.className="revoke";revoke.textContent="Revoke";revoke.addEventListener("click",()=>removeClient(client,revoke));row.append(name,meta,toggle,revoke);return row}
function renderClients(clients){const list=$("clientList");list.replaceChildren(...clients.map(clientRow));$("emptyState").hidden=clients.length>0}
async function refresh(){const result=await api("/clients");renderClients(result.clients||[]);updateSummary(result.summary);if(!$("publicUrl").value&&result.public_url)$("publicUrl").value=result.public_url}
async function changeAccess(id,enabled,button){setBusy(button,true,"Saving…");try{const result=await api(`/clients/${encodeURIComponent(id)}/enabled`,{method:"POST",body:JSON.stringify({enabled})});updateSummary(result.summary);await refresh();toast(enabled?"Friend access restored.":"Friend access paused immediately.")}catch(error){toast(error.message)}finally{setBusy(button,false,"Saving…")}}
async function removeClient(client,button){if(!confirm(`Permanently revoke ${client.name}? They will need a new QR code to reconnect.`))return;setBusy(button,true,"Revoking…");try{const result=await api(`/clients/${encodeURIComponent(client.id)}`,{method:"DELETE"});updateSummary(result.summary);await refresh();toast("Device revoked.")}catch(error){toast(error.message)}finally{setBusy(button,false,"Revoking…")}}
async function createInvitation(){const button=$("createPairing");setBusy(button,true,"Generating…");try{const result=await api("/pairings",{method:"POST",body:JSON.stringify({label:$("friendLabel").value.trim()||"Friend's device",public_url:$("publicUrl").value.trim(),expires_minutes:Number($("expiresMinutes").value)})});activePairing=result.pairing;$("pairingTitle").textContent=activePairing.label;$("pairingExpiry").textContent=`Expires ${formatSeen(activePairing.expires_at)} and works once.`;$("pairingQr").src=activePairing.qr_data_uri;$("pairingCard").hidden=false;$("pairingCard").scrollIntoView({behavior:"smooth",block:"center"})}catch(error){toast(error.message)}finally{setBusy(button,false,"Generating…")}}
async function copyValue(value,message){try{await navigator.clipboard.writeText(value);toast(message)}catch{toast("Copy was blocked. Select the link manually.")}}
async function unlock(){const button=$("unlockButton");adminKey=$("adminKey").value.trim();if(!adminKey)return void($("unlockError").textContent="Enter the admin key shown on the PC.");setBusy(button,true,"Checking…");try{const status=await api("/status");unlockDashboard();updateSummary(status.summary);if(status.public_url)$("publicUrl").value=status.public_url;await refresh();$("unlockError").textContent=""}catch(error){$("unlockError").textContent=error.message}finally{setBusy(button,false,"Checking…")}}
$("unlockButton").addEventListener("click",unlock);$("adminKey").addEventListener("keydown",event=>{if(event.key==="Enter")unlock()});$("lockButton").addEventListener("click",lockDashboard);$("refreshButton").addEventListener("click",()=>refresh().catch(error=>toast(error.message)));$("createPairing").addEventListener("click",createInvitation);$("closePairing").addEventListener("click",()=>$("pairingCard").hidden=true);$("copyAppLink").addEventListener("click",()=>activePairing&&copyValue(activePairing.app_url,"App pairing link copied."));$("copyWebLink").addEventListener("click",()=>activePairing&&copyValue(activePairing.web_url,"Browser fallback copied."));
if(adminKey){$("adminKey").value=adminKey;unlock()}setInterval(()=>{if(adminKey&&!$("dashboardView").hidden)refresh().catch(()=>{})},10000);
